### PR TITLE
DONT DOWNLOAD ITS A TROLL

### PR DESCRIPTION
**Pull request by ghost**
**IF YOU ARE READING THIS ITS A GAY MOD MEANT TO TRICK PEOPLE WANTING TO REMOVE THE PRIDE FLAGS**

**HERE IS LEGIT LINKS**
https://archive.org/download/non-newtonian-new-york-58-1-0-1660526891_202208
https://drive.google.com/file/d/1-FEQV2u_xEVm4ccmzw72QCE6HgCZKN3-/view

**how to install the ACTUAL mod >>**

first download the Non-Newtonian New York MOD created by MikeHawk232323231, which our friend Valentino Makaveli made available to us

preferably extract the file to an easy-to-find location.

now download the modding tool Created by

jedijosh920 here > https://www.nexusmods.com/marvelsspidermanremastered/mods/51

if you don't have a nexus account download it here > https://www.mediafire.com/file/vvoz7j7svapmmbi/SpiderManPCTool-51-v1-0-0-1660516141.zip/file

extract the files anywhere, now launch the modding tool by clicking "SMPCTool.exe".

a tool window will open, now you need to locate the "asset_archive" folder (this folder is in \Marvel's Spider-Man Remastered\asset_archive) click "File" then "Select Asset Archive Folder". locate the "asset_archive" folder " and click Save.

still in the tool window, click "Install Mod", now locate the mod file you downloaded "NNNY.smpcmod" click open.

another window will open, now click on "INSTALL MOD"... wait for the installation process... at the end you should get the message "Successfully installed Spider-Man Mod!" of an ok.

now you can close the tool window and start the Spider-Man game, and enjoy the MOD Non-Newtonian New York created by MikeHawk232323231

### CODE REVIEW

**Comment by ghost** [comment]
Thanks!
I really wanted to get rid of those shitflags, really appreciated!

**Comment by ghost** [comment]
> Thanks! I really wanted to get rid of those shitflags, really appreciated!

No problem brother, not trying to let anyone else accidentally get their Spiderman game blasted with pink

**Comment by GioMetal** [comment]
What is funny is that the author thinks he's a programmer all he can do is at best scripting with js or python, and thinks html is programming.

**Comment by skMetinek** [comment]
Bullshit, the file isn't damaged or changed. The only thing that makes sense in your pull request is how to install the mod, which probably shouldn't be a problem. If anyone has doubts, I recommend that you go ahead and check the CRC of the file from my github, and from these legit links. 

Again, I'm not the author. The author has been included in the readme file. It's just a permanent reupload so no one will think of censoring freedom of speech.

Stop being mad ;*
proof

**Comment by CatFoodBowl** [comment]
Its actually fake. guys listen to GHOST. this piece of trash github download is fake, use the google one from ghost, and get away from the pedophilia!!

**Pull request closed without merging**
